### ISSUE TITLE
Snowflake Schemas_filter not working

### ISSUE THREAD

**Issue by ysantanar** [opendatadiscovery/odd-collectors#113]
I try to filter the schemas with a regular expression pattern but it doesn't work. It gets all the Snowflake entities.
![image](https://github.com/user-attachments/assets/e8b1ec1a-f679-4c87-8901-2582ad3205fe)

**Comment by ysantanar** [comment]
I think the problem was the regular expression. It couldn't be a previous run because it's a new deployment and between tests I deleted the dockers.

Thanks!

**Comment by ValeriyWorld** [comment]
@ysantanar Did you manage to successfully ingest metadata with a filter? Can the issue be closed?

**Comment by ysantanar** [comment]
Yes, I was able to filter the schemes. Thanks
