### ISSUE TITLE
Investigate how to make error response for 400 from the platform more verbose

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-collectors#39]
For now we do not see in the logs of collector information from the platform why it rejects requests with Bad Request status.

**Comment by ValeriyWorld** [comment]
@RamanDamayeu I don't see the opportunity to increase the readability of error logging for this case. We are using API for data source and data entity ingestions and just using it's response information for logging inside collector. I dived into the possible genesis of this particular error:
```
2024-01-10 11:01:20.317 | ERROR   | odd_collector_sdk.collector:run:137 - Could not create data sources. Reason: 400, message='Bad Request', url=URL('http://odd-platform:8080/ingestion/datasources[')](http://odd-platform:8080/ingestion/datasources%27))
```
Reproduced it and there was not any additional useful information in the API response. I think if we need to handle some specific cases it should be implemented on the back-end side at first.
