### ISSUE TITLE
Collector should handle error code/message from the platform

### ISSUE THREAD

**Issue by Vladysl** [opendatadiscovery/odd-collectors#66]
Platform response 

<img width="930" alt="image" src="https://github.com/opendatadiscovery/odd-collectors/assets/45620393/9e7f926e-ba3e-445a-b5a6-f006fefbc4a4">
collector's logs 

<img width="1272" alt="image" src="https://github.com/opendatadiscovery/odd-collectors/assets/45620393/318af3dd-6432-4fdb-b280-f84872ac81e9">

**Comment by ValeriyWorld** [comment]
Error handling added with #99 
Example of response with error:
![image](https://github.com/user-attachments/assets/de1dbb34-fb6b-4aac-9bd8-8ce2a6ecd954)
