### ISSUE TITLE
Manage release of different collectors (generic, aws, azure, gcp)

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-collectors#82]
To handle different collector releases from the same repository:
1. We need to have different "tag" streams for different collectors, e. g. generic/1.0.0, aws/1.0.0, azure/1.0.0, gcp/1.0.0;
2. Release on the repository should be specific for collector type as well, e. g. "Generic ODD Collector 1.0.0", "AWS ODD Collector 1.0.0", "Azure ODD Collector 1.0.0", "GCP ODD Collector 1.0.0"; 
3. GitActions should include in the logic the release pattern and tag pattern.

**Comment by RamanDamayeu** [comment]
PR: https://github.com/opendatadiscovery/odd-collectors/pull/83

**Comment by ValeriyWorld** [comment]
PR #83 does not contain all the needed changes. Main PR: #86 , with the last working fixes.
